### ISSUE TITLE
Unit tests fail with /usr/bin/ld: -lhts not found

### ISSUE THREAD

**Issue by ardakdemir** [ratschlab/graph_annotation#1]
RESOLVED!!!

This issue is resolved after adding the path to the htslib 

Dear @hmusta ,

I am trying to reproduce the results in your paper. Currently I am trying to build the environment to run the program. When I follow your steps and run the unit_tests I get the following error message at [ 58%] Linking CXX executable annograph:

/usr/bin/cmake3 -E cmake_link_script CMakeFiles/annograph.dir/link.txt --verbose=1
/usr/local/package/gcc/7.3.0/bin/g++  -I/usr/local/include   -std=c++14 -Wall -Wextra -Werror -Wno-ignored-qualifiers   -msse4.2 -mavx -mavx2 -mbmi -mbmi2 -g   -fopenmp -D_THREAD_SAFE -pthread -O2 -g  -L/usr/local/lib64 -L/usr/local/lib CMakeFiles/annograph.dir/main.cpp.o  -o annograph  -L/home/aakdemir/graph_annotation/external-libraries/sdsl-lite/lib -Wl,-rpath,/home/aakdemir/graph_annotation/external-libraries/sdsl-lite/lib libannographlibs.a -lhts -lz -lbz2 -lssl -lcrypto -llzma -lsdsl -lgmp bloom_annotator/libbloom_annotator.a wavelet_trie/libwtr_libs.a -lsdsl 

/usr/bin/ld: -lhts  could not find link_directories list in CMakeFileLists.txt

I wonder if you have encountered such an error. I think it can be related to the way I installed sdsl-lite but I just followed the suggested command in the github page.

Kind regards

Arda

**Comment by hmusta** [comment]
It looks like it can't find the HTSlib libs (libhts.a or libhts.so).

Try adding the directory that contains the files I mentioned above after line 27 in `CMakeFileLists.txt` (in the `link_directories` list).

**Comment by ardakdemir** [comment]
Thanks for your reply!

I figured it out myself eventually but forgot to close the issue.
